//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthelloWebApplication.OthelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/", ConfigurationName="OthelloService.OthelloWebService")]
    public interface OthelloWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/OthelloWebService/infoPlayerRequest", ReplyAction="http://webservice/OthelloWebService/infoPlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OthelloWebApplication.OthelloService.infoPlayerResponse infoPlayer(OthelloWebApplication.OthelloService.infoPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/OthelloWebService/infoPlayerRequest", ReplyAction="http://webservice/OthelloWebService/infoPlayerResponse")]
        System.Threading.Tasks.Task<OthelloWebApplication.OthelloService.infoPlayerResponse> infoPlayerAsync(OthelloWebApplication.OthelloService.infoPlayerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/OthelloWebService/helloRequest", ReplyAction="http://webservice/OthelloWebService/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OthelloWebApplication.OthelloService.helloResponse hello(OthelloWebApplication.OthelloService.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/OthelloWebService/helloRequest", ReplyAction="http://webservice/OthelloWebService/helloResponse")]
        System.Threading.Tasks.Task<OthelloWebApplication.OthelloService.helloResponse> helloAsync(OthelloWebApplication.OthelloService.helloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class playerProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private int winsField;
        
        private int lossField;
        
        private string[] gameListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int wins {
            get {
                return this.winsField;
            }
            set {
                this.winsField = value;
                this.RaisePropertyChanged("wins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int loss {
            get {
                return this.lossField;
            }
            set {
                this.lossField = value;
                this.RaisePropertyChanged("loss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] gameList {
            get {
                return this.gameListField;
            }
            set {
                this.gameListField = value;
                this.RaisePropertyChanged("gameList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="infoPlayer", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class infoPlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public infoPlayerRequest() {
        }
        
        public infoPlayerRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="infoPlayerResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class infoPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OthelloWebApplication.OthelloService.playerProfile @return;
        
        public infoPlayerResponse() {
        }
        
        public infoPlayerResponse(OthelloWebApplication.OthelloService.playerProfile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OthelloWebServiceChannel : OthelloWebApplication.OthelloService.OthelloWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OthelloWebServiceClient : System.ServiceModel.ClientBase<OthelloWebApplication.OthelloService.OthelloWebService>, OthelloWebApplication.OthelloService.OthelloWebService {
        
        public OthelloWebServiceClient() {
        }
        
        public OthelloWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OthelloWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OthelloWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OthelloWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OthelloWebApplication.OthelloService.infoPlayerResponse OthelloWebApplication.OthelloService.OthelloWebService.infoPlayer(OthelloWebApplication.OthelloService.infoPlayerRequest request) {
            return base.Channel.infoPlayer(request);
        }
        
        public OthelloWebApplication.OthelloService.playerProfile infoPlayer(string username) {
            OthelloWebApplication.OthelloService.infoPlayerRequest inValue = new OthelloWebApplication.OthelloService.infoPlayerRequest();
            inValue.username = username;
            OthelloWebApplication.OthelloService.infoPlayerResponse retVal = ((OthelloWebApplication.OthelloService.OthelloWebService)(this)).infoPlayer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OthelloWebApplication.OthelloService.infoPlayerResponse> OthelloWebApplication.OthelloService.OthelloWebService.infoPlayerAsync(OthelloWebApplication.OthelloService.infoPlayerRequest request) {
            return base.Channel.infoPlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<OthelloWebApplication.OthelloService.infoPlayerResponse> infoPlayerAsync(string username) {
            OthelloWebApplication.OthelloService.infoPlayerRequest inValue = new OthelloWebApplication.OthelloService.infoPlayerRequest();
            inValue.username = username;
            return ((OthelloWebApplication.OthelloService.OthelloWebService)(this)).infoPlayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OthelloWebApplication.OthelloService.helloResponse OthelloWebApplication.OthelloService.OthelloWebService.hello(OthelloWebApplication.OthelloService.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            OthelloWebApplication.OthelloService.helloRequest inValue = new OthelloWebApplication.OthelloService.helloRequest();
            inValue.name = name;
            OthelloWebApplication.OthelloService.helloResponse retVal = ((OthelloWebApplication.OthelloService.OthelloWebService)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OthelloWebApplication.OthelloService.helloResponse> OthelloWebApplication.OthelloService.OthelloWebService.helloAsync(OthelloWebApplication.OthelloService.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<OthelloWebApplication.OthelloService.helloResponse> helloAsync(string name) {
            OthelloWebApplication.OthelloService.helloRequest inValue = new OthelloWebApplication.OthelloService.helloRequest();
            inValue.name = name;
            return ((OthelloWebApplication.OthelloService.OthelloWebService)(this)).helloAsync(inValue);
        }
    }
}
